name: Manually run by $(Build.RequestedFor) on $(Date:dd-MM-yyyy)$(Rev:.r) -
trigger: none

parameters:
  - name: resourcegroupName
    type: string
    default: "_rg-WPNS-demo"
  - name: hostpoolName
    type: string
    default: "hp-demo-wpns-ado"

stages:
  - stage: "AzureResourceDeployment"
    displayName: "Azure resource deployment"
    jobs:
      - job: "BicepTemplateDeployment"
        timeoutInMinutes: 15
        displayName: "Bicep template deployment"
        pool:
          vmImage: "windows-latest"
        workspace:
          clean: all
        steps:
          - checkout: self
          # ARM template deployment v3 | Deploy a resource, using a Bicep template.
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              # Azure Details
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'VisualStudioEnterprise'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '${{parameters.resourcegroupName}}'
              location: 'westeurope'
              # Template
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)\deployADO.bicep'
              overrideParameters: '-hostpoolName ${{parameters.hostpoolName}}'
              deploymentMode: "Incremental"
